version: "3.9"

services: 
  nginx:
    depends_on:
      - frontend
      - collab-service
      - matching-service
      - user-service
      - question-service
      - communication-service
    image: nginx
    ports:
      - 80:80
    build:
      context: ./nginx
    restart: always

  frontend:
    image: frontend
    build:
      context: ./frontend
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
  
  collab-service:
    image: collab-service
    build:
      context: ./collab-service

  matching-service:
    image: matching-service
    build:
      context: ./matching-service
  
  user-service:
    image: user-service
    build:
      context: ./user-service
  
  question-service:
    image: question-service
    build:
      context: ./question-service

  communication-service:
    image: communication-service
    build:
      context: ./communication-service