# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  user-service:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: user-service

    strategy:
      matrix:
        node-version: [16.x, 18.x]
        mongodb-version: ['5.0', '6.0']
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.8.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}
    - run: npm install
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
      env:
        DB_LOCAL_URI: mongodb+srv://admin:q0RqQon9AYeZSoHt@cluster0.thnlshk.mongodb.net/myDb?retryWrites=true&w=majority
        JWT_SECRET_KEY: testSecretKey

  
  question-service:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: question-service

    strategy:
      matrix:
        node-version: [16.x, 18.x]
        mongodb-version: ['5.0', '6.0']
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.8.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}
    - run: npm install
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
  
  collab-service:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: collab-service

    strategy:
      matrix:
        node-version: [16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
  
  matching-service:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: matching-service

    strategy:
      matrix:
        node-version: [16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test